### ISSUE TITLE
Rename?

### ISSUE THREAD

**Issue by lucasvreis** [lucasvreis/org-mode-hs#7]
With #6, this is becoming more than just a parser. `org-mode` and `orgmode` and already taken in Hackage. Some ideas:
- `org-hs`
- Just `org`?
- Leave it as it is :(

**Comment by srid** [comment]
Split into multiple libraries ?

**Comment by lucasvreis** [comment]
> Split into multiple libraries ?

This makes sense, although it would be nice to have a common prefix to the libraries, and just `org` feels a bit pretentious. Maybe the `org-parser` prefix is fine, and I would do this:
- `org-parser` -> parser
- `org-parser-cli` -> provides a `org-hs` executable
- `org-parser-exporters` -> common exporter functionality
- `org-parser-html`
- `org-parser-pandoc`
- ...

**Comment by srid** [comment]
What do the last two mean?

**Comment by lucasvreis** [comment]
The `org-parser-exporters` library would basically include the [`Org.Exporters.Common`](https://github.com/lucasvreis/org-parser/blob/multitype/src/Org/Exporters/Common.hs) file, that exports the `ExportBackend` class. Other libraries can create export backends by instantiating this class.

The name is awkward but [`org-parser-html`](https://github.com/lucasvreis/org-parser/blob/multitype/src/Org/Exporters/HTML.hs) and [`org-parser-pandoc`](https://github.com/lucasvreis/org-parser/blob/multitype/src/Org/Exporters/Pandoc.hs) basically just do this, I wrote the last two like that because `org-parser-exporter-html` and `org-parser-pandoc` are too awkward... lol

**Comment by srid** [comment]
- `horg` -> cli exectuable
- `horg-parser` -> the parser and AST
- `horg-exporter` -> exporter core, along with default exporters (html and pandoc)
   -  can further be split into `horg-exporter`, `horg-exporter-html` and `horg-exporter-pandoc` if really must

**Comment by lucasvreis** [comment]
This division makes sense, but isn't `org-hs` better than `horg`?

**Comment by srid** [comment]
I'm not even a fan of `horg`; I'd come up with a really unique and memorable name, like [Orgile](https://orgmode.org/worg/org-tools/index.html).

**Comment by lucasvreis** [comment]
I think I'll do this: since it's available, the common prefix will be just `org` (so `org-parser`, `org-cli`, `org-exporters`). If people complain, `yaorg`. For some reason the other names sound to me like they're either about an app or some sort of new markup language, different from emac's org.
